### ISSUE TITLE
Error while gradle sync

### ISSUE THREAD

**Issue by lectricas** [VictorAlbertos/RxPermissionsResult#1]
Error:Could not find com.github.VictorAlbertos:RxPermissionsResult:rx1.
Required by:
    fixedrec4_1:app:unspecified
<a href="searchInBuildFiles">Search in build.gradle files</a>

Just copied and pasted rxjava 1 compile strings...

**Comment by VictorAlbertos** [comment]
So far no one has notified any problem trying to import the library. 

Did you manage to solve it?

**Comment by onomated** [comment]
Just encountered the same issue.  Didn't work by copying the gradle link from the readme, but works fine with I copied directly from [jitpack](https://jitpack.io/#VictorAlbertos/RxPermissionsResult/0.0.4)
```
compile 'com.github.VictorAlbertos.RxPermissionsResult:rx2:0.0.4'
```

**Comment by VictorAlbertos** [comment]
Thanks for pointing that out. I've already updated the README
